// Single source of truth for "path -> friendly label" -- used by App.jsx for the
// document.title tag AND by tabsContext.jsx for tab labels, so the two can never
// drift out of sync (extracted from App.jsx, which used to keep this inline).
export const PAGE_TITLES = {
  '/': 'Summary',
  '/dashboard/overall': 'Overall',
  '/dashboard/overall-bigquery': 'Overall (BigQuery)',
  '/dashboard/ceo-b2c-pnl': 'Daily P&L',
  '/dashboard/ceo-b2c-cashflow': 'Daily Cash Flow',
  '/dashboard/marketing-review': 'Marketing Review',
  '/dashboard/meta-ads': 'Meta Ads',
  '/dashboard/leverage-careers': 'Leverage Careers',
  '/dashboard/apps': 'Apps',
  '/dashboard/google-ads': 'Google Ads',
  '/dashboard/roas': 'ROAS',
  '/dashboard/mtd': 'MTD',
  '/dashboard/revenue': 'Revenue',
  '/dashboard/organic-social': 'Organic & Social',
  '/dashboard/lq-ops': 'Daily QLs',
  '/dashboard/lq-ops-monthly': 'Monthly QLs',
  '/dashboard/lq-ops-detail': 'Human QL Detail',
  '/dashboard/lq-ops-ai-detail': 'AI QL Detail',
  '/dashboard/lq-ops-human-unassigned': 'Human Unassigned',
  '/dashboard/lq-ops-ai-unassigned': 'AI Unassigned',
  '/dashboard/futwork-errors': 'Futwork Errors',
  '/dashboard/lq-field-schema': 'Field Schema',
  '/dashboard/whatsapp': 'WhatsApp',
  '/dashboard/referral': 'Referral',
  '/dashboard/leads-assigned': 'Leads Assigned',
  '/dashboard/leadsquared': 'LeadSquared',
  '/dashboard/live-qls': 'Live QLs',
  '/dashboard/team-mapping': 'Team Mapping',
  '/dashboard/super-tracker': 'Super Tracker',
  '/ask-ai': 'Ask AI',
  '/dashboard/agents': 'Agents',
  '/dashboard/marketing-performance': 'Marketing Performance',
  '/settings': 'Settings',
  '/settings/reports/email': 'Email Reports',
  '/settings/reports/slack': 'Slack',
}
