import { useState, useEffect } from 'react'
import { useAuth } from '../hooks/useAuth'
import Sidebar from '../components/Sidebar'
import styles from './AIInsights.module.css'

export default function AIInsights() {
  const { user } = useAuth()
  const isAdmin = user?.role === 'admin'

  const [insight, setInsight] = useState(null)
  const [loading, setLoading] = useState(true)
  const [generating, setGenerating] = useState(false)
  const [error, setError] = useState(null)

  const load = async () => {
    setLoading(true)
    setError(null)
    try {
      const r = await fetch('/api/insights', { credentials: 'include' })
      const d = await r.json()
      if (!r.ok) throw new Error(d.error || 'Could not load insights')
      setInsight(d.insight)
    } catch (e) {
      setError(e.message)
    } finally {
      setLoading(false)
    }
  }

  useEffect(() => { load() }, [])

  const regenerate = async () => {
    setGenerating(true)
    setError(null)
    try {
      const r = await fetch('/api/generate-insights', { method: 'POST', credentials: 'include' })
      const d = await r.json()
      if (!r.ok) throw new Error(d.error || 'Could not generate analysis')
      await load()
    } catch (e) {
      setError(e.message)
    } finally {
      setGenerating(false)
    }
  }

  const updated = insight?.created_at
    ? new Date(insight.created_at).toLocaleString('en-IN', { day: '2-digit', month: 'short', year: 'numeric', hour: '2-digit', minute: '2-digit' })
    : null

  return (
    <div className={styles.layout}>
      <Sidebar />
      <div className={styles.main}>

        <div className={styles.header}>
          <div>
            <div className={styles.eyebrow}>Intelligence</div>
            <h1 className={styles.title}>AI Insights</h1>
            <p className={styles.subtitle}>
              Weekly performance analysis generated by Claude{insight?.model ? ` (${insight.model})` : ''}.
              {updated ? ` Last updated ${updated}.` : ''}
            </p>
          </div>
          {isAdmin && (
            <button className={styles.regenBtn} onClick={regenerate} disabled={generating}>
              {generating ? (
                <><span className={styles.spinner} /> Analysing…</>
              ) : (
                <>
                  <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round">
                    <path d="M23 4v6h-6M1 20v-6h6" /><path d="M3.51 9a9 9 0 0114.85-3.36L23 10M1 14l4.64 4.36A9 9 0 0020.49 15" />
                  </svg>
                  Regenerate now
                </>
              )}
            </button>
          )}
        </div>

        {error && <div className={styles.errorBox}>⚠️ {error}</div>}

        <div className={styles.card}>
          {loading ? (
            <div className={styles.center}><span className={styles.spinner} /> Loading insights…</div>
          ) : generating ? (
            <div className={styles.center}><span className={styles.spinner} /> Claude is analysing your latest data…</div>
          ) : insight?.html ? (
            <>
              <div className={styles.periodPill}>{insight.period}</div>
              <div className={styles.content} dangerouslySetInnerHTML={{ __html: insight.html }} />
            </>
          ) : (
            <div className={styles.empty}>
              <div className={styles.emptyIcon}>
                <svg width="26" height="26" viewBox="0 0 24 24" fill="none" stroke="#9CA3AF" strokeWidth="1.5" strokeLinecap="round">
                  <path d="M9 18h6M10 22h4M12 2a7 7 0 00-4 12.7V17h8v-2.3A7 7 0 0012 2z" />
                </svg>
              </div>
              <p>No analysis generated yet.</p>
              {isAdmin
                ? <p className={styles.emptyHint}>Click “Regenerate now” to create the first one.</p>
                : <p className={styles.emptyHint}>The weekly analysis will appear here once it runs.</p>}
            </div>
          )}
        </div>

      </div>
    </div>
  )
}
