import { getSessionUser, supabaseAdmin } from '../lib/auth.mjs'

// Returns the latest stored AI insight for the dashboard. Read-only, and only
// for signed-in users — the analysis itself is generated by generate-insights.
export default async function handler(req, res) {
  if (req.method !== 'GET') return res.status(405).json({ error: 'Method not allowed' })

  const me = getSessionUser(req)
  if (!me) return res.status(401).json({ error: 'Not signed in' })

  try {
    const r = await supabaseAdmin('ai_insights?select=html,period,model,created_at&order=created_at.desc&limit=1')
    const rows = await r.json()
    return res.status(200).json({ insight: rows?.[0] || null })
  } catch (e) {
    return res.status(500).json({ error: e.message })
  }
}
